# Generated by Django 3.1.2 on 2020-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(default='Mangalore', max_length=50)),
                ('category', models.CharField(choices=[('NGO', 'NGO'), ('Old Age Home', 'Old Age Home'), ('Orphanage', 'Orphanage'), ('Social Initiative', 'Social Initiative')], default='NGO', max_length=30)),
                ('description', models.TextField(default='Description', max_length=200)),
                ('donation_required', models.BooleanField(default=False)),
                ('amt_needed', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('amt_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
