# Generated by Django 3.1.2 on 2020-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='donate',
            field=models.BooleanField(default=False),
        ),
    ]
