# Generated by Django 3.1.2 on 2020-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20201118_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='descrip',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='donate',
            new_name='donation_required',
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('NGO', 'NGO'), ('Old Age Home', 'Old Age Home'), ('Orphanage', 'Orphanage'), ('Social Initiative', 'Social Initiative')], default='NGO', max_length=30),
        ),
    ]
